kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: bankapp-admin-rolebinding
  namespace: bankapp

subjects:
- kind: User
  name: sarvesh-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: bankapp-admin
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bankapp-viewer-rolebinding
  namespace: bankapp

subjects:
- kind: User
  name: mac-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: bankapp-viewer
  apiGroup: rbac.authorization.k8s.io 

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bankapp-read-write-rolebinding
  namespace: bankapp

subjects:
- kind: User
  name: fastrack-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: bankapp-read-write
  apiGroup: rbac.authorization.k8s.io
