kind: ServiceAccount
apiVersion: v1
metadata:
   name: sarvesh-user
   namespace: bankapp
---
kind: ServiceAccount
apiVersion: v1
metadata:
   name: mac-user
   namespace: bankapp
---
kind: ServiceAccount
apiVersion: v1
metadata:
   name: fastrack
   namespace: bankapp
