apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  namespace: bankapp-prod
  labels:
    app: bankapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp

  template:
    metadata:
      labels:
        app: bankapp

    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ["/bin/sh","-c","until nc -z mysql-service 3306; do sleep 2; done"]
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"

      containers:
        - name: bankapp
          image: sarvesh01234/ai-bankapp:628fbb3e7581e2f5736f60609f4fcc7144aaaab6
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bankapp-configmap
            - secretRef:
                name: bankapp-secrets
