apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-prod
  namespace: bankapp-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
       app: mysql
