apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  namespace: bankapp
  labels:
    app: bankapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp

  template:
    metadata:
      labels:
        app: bankapp

    spec:
      initContainers:
        - name: wait-for-mysql
          image: sarvesh01234/ai-bankapp:89ec34d22ee6ba340d401a851d4043ea2e3085b0
          command: ["/bin/sh","-c","until nc -z mysql-service 3306; do sleep 2; done"]
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"

      containers:
        - name: bankapp
          image: sarvesh01234/ai-bankapp:89ec34d22ee6ba340d401a851d4043ea2e3085b0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bankapp-configmap
            - secretRef:
                name: bankapp-secrets
